services:
  db-service:
    build:
      context: ../services/db-service
      dockerfile: dockerfile.dev
    container_name: db-service-dev
    ports:
      - "5432:3000"
    volumes:
      - ../services/db-service:/app
    environment:
      NODE_ENV: development
    working_dir: /app

  auth-service:
    build:
      context: ../services/auth-service
      dockerfile: dockerfile.dev
    container_name: auth-service-dev
    ports:
      - "4001:3000"
    volumes:
      - ../services/auth-service:/app
    environment:
      NODE_ENV: development
    working_dir: /app

  chat-service:
    build:
      context: ../services/chat-service
      dockerfile: dockerfile.dev
    container_name: chat-service-dev
    ports:
      - "4002:3000"
    volumes:
      - ../services/chat-service:/app
    environment:
      NODE_ENV: development
    working_dir: /app

  gateway-service:
    build:
      context: ../services/gateway-service
      dockerfile: dockerfile.dev
    container_name: gateway-service-dev
    ports:
      - "4003:3000"
    volumes:
      - ../services/gateway-service:/app
    environment:
      NODE_ENV: development
    working_dir: /app

  lobby-service:
    build:
      context: ../services/lobby-service
      dockerfile: dockerfile.dev
    container_name: lobby-service-dev
    ports:
      - "4004:3000"
    volumes:
      - ../services/lobby-service:/app
    environment:
      NODE_ENV: development
    working_dir: /app

  matchmaking-service:
    build:
      context: ../services/matchmaking-service
      dockerfile: dockerfile.dev
    container_name: matchmaking-service-dev
    ports:
      - "4005:3000"
    volumes:
      - ../services/matchmaking-service:/app
    environment:
      NODE_ENV: development
    working_dir: /app

  notification-service:
    build:
      context: ../services/notification-service
      dockerfile: dockerfile.dev
    container_name: notification-service-dev
    ports:
      - "4006:3000"
    volumes:
      - ../services/notification-service:/app
    environment:
      NODE_ENV: development
    working_dir: /app

  tournament-service:
    build:
      context: ../services/tournament-service
      dockerfile: dockerfile.dev
    container_name: tournament-service-dev
    ports:
      - "4007:3000"
    volumes:
      - ../services/tournament-service:/app
    environment:
      NODE_ENV: development
    working_dir: /app

  user-service:
    build:
      context: ../services/user-service
      dockerfile: dockerfile.dev
    container_name: user-service-dev
    ports:
      - "4008:3000"
    volumes:
      - ../services/user-service:/app
    environment:
      NODE_ENV: development
    working_dir: /app

