FROM owasp/modsecurity-crs:nginx

# Optional: copy your custom config
COPY nginx.conf /etc/nginx/nginx.conf
COPY modsecurity.conf /etc/modsecurity/modsecurity.conf

CMD sh -c '\
  touch /tmp/nginx-waiting;\
  for host in $WAIT_FOR_HOSTS; do \
    until getent hosts "$host"; do \
      echo "⏳ Waiting for $host..."; \
      sleep 1; \
    done; \
    echo "✅ $host resolved."; \
  done; \
  exec nginx -g "daemon off;"; \
'
